### get user's lists
GET http://localhost:5000/jurek/lists

### add list
POST http://localhost:5000/jurek/lists/add
Content-Type: application/json

{
    "name": "Shopping list",
    "color": "e3ff00"
}

### remove list with given id
POST http://localhost:5000/jurek/lists/remove
Content-Type: application/json

{
    "id": "636d34304a38e0092fde5fec"
}
### add item to a list with a given id
POST http://localhost:5000/jurek/lists/items/add
Content-Type: application/json

{
    "listId": "636d319cc1acdf944d2945a2",
    "name": "item 4",
    "date": null
}

### edit an item of a list
POST http://localhost:5000/jurek/lists/items/edit
Content-Type: application/json

{
    "listId": "636d319cc1acdf944d2945a2",
    "itemId": "637dfa519485db695fbe9f61",
    "name": "ITEM no 2"
}
### edit status of an item of a list
POST http://localhost:5000/jurek/lists/items/edit-status
Content-Type: application/json

{
    "listId": "636d319cc1acdf944d2945a2",
    "itemId": "637dfa519485db695fbe9f61"
}

### remove an item of a list
POST http://localhost:5000/jurek/lists/items/remove
Content-Type: application/json

{
    "listId": "636d319cc1acdf944d2945a2",
    "itemId": "636d32554b991968997d8613"
}